name: cicd

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-2022
          - windows-2025
        version:
          - "9.3.0-preview.1.25265.20"
          - "9.4.0-preview.1.25378.8"
          - "9.5.0-preview.1.25474.7"
        include:
          - platform: ltsc2022
            parent_image: mcr.microsoft.com/dotnet/aspnet:9.0-nanoserver-ltsc2022
            os: windows-2022

          - platform: ltsc2025
            parent_image: mcr.microsoft.com/dotnet/aspnet:9.0-nanoserver-ltsc2025
            os: windows-2025

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build and push
        run: |
          $version = "${{ matrix.version }}"
          $shortVersion = $version.Substring(0, 5)
          $parentImage = "${{ matrix.parent_image }}"
          $tag = "ghcr.io/pbering/dotnet-aspire-dashboard-windows:$shortVersion-${{ matrix.platform }}"

          Write-Host "version: $version"
          Write-Host "shortVersion: $shortVersion"
          Write-Host "tag: $tag"
          Write-Host "parent_image: $parentImage"

          #docker build --build-arg ASPIRE_VERSION=${{ matrix.version }} --build-arg PARENT_IMAGE=$parentImage --tag $tag .
          #docker push $tag
