name: cicd

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-2022
          - windows-2025
        version:
          - "8.1.0"
          - "9.0.0-preview.5.24551.3"
          - "9.1.0-preview.1.25121.10"
          - "9.3.0-preview.1.25265.20"
          - "9.4.0-preview.1.25378.8"
          - "9.5.0-preview.1.25474.7"
        include:
          - platform: ltsc2022
            parent_image: mcr.microsoft.com/dotnet/aspnet:9.0-nanoserver-ltsc2022

          - platform: ltsc2025
            parent_image: mcr.microsoft.com/dotnet/aspnet:9.0-nanoserver-ltsc2025

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      # - name: Docker login
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build and push
        run: |
          $shortVersion = "${{ matrix.version }}".Substring(0, 5)
          $tag = "ghcr.io/pbering/dotnet-aspire-dashboard-windows:$shortVersion-${{ matrix.platform }}"

          #docker build --build-arg ASPIRE_VERSION=${{ matrix.version }} --build-arg PARENT_IMAGE=${{ matrix.parent_image }} --tag $tag .
          #docker push $tag
